### ISSUE TITLE
cpu.sh returns incorrect results on macOS with multiple disk drives

### ISSUE THREAD

**Issue by RafalLukawiecki** [samoshkin/tmux-plugin-sysstat#2]
...because it reads the wrong column:

<img width="547" alt="screen shot 2017-12-11 at 13 34 26" src="https://user-images.githubusercontent.com/22912705/33833954-3fc16a30-de79-11e7-8106-b6ede9b4f1a8.png">

<img width="225" alt="screen shot 2017-12-11 at 13 34 54" src="https://user-images.githubusercontent.com/22912705/33833960-459b31de-de79-11e7-9873-c034e54c4622.png">

and shows (on an idle system):

<img width="67" alt="screen shot 2017-12-11 at 13 35 18" src="https://user-images.githubusercontent.com/22912705/33833972-4ebfb76c-de79-11e7-9c61-835d8fa11101.png">

PR on its way.

**Comment by samoshkin** [comment]
Yeah, just noticed the same issue yesterday, when plug my USB stick. Seems, needs get rid of $6th column, and take Nth column from the end, rather than from beginning. Or limit the output to single disk only. Will fix it soon. @RafalLukawiecki Thank you for you involvement.

**Comment by RafalLukawiecki** [comment]
You are welcome. See PR #3

**Comment by samoshkin** [comment]
Yeah, that's what I meant. :) Merged.
